# Generated by Django 4.2.3 on 2023-07-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgeditor', '0004_alter_imagefile_processed_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='processed_img',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
